#!/bin/bash

# SETUP MTU
ip link set enp65s0 down
ip link set enp66s0 down



# SETUP DRBD REPLICATION
ip link add link mlnx-bond name drbd type vlan id 10
ip link set drbd mtu 9000
ip link set drbd up
ip addr add 4.1.0.12/24 dev drbd

# Setup NFS Share
ip link add link mlnx-bond name nfs type vlan id 15
ip link set nfs up
ip addr add 4.115.0.12/24 dev nfs 

# SETUP LINSTOR MGMT 
ip link add link mlnx-bond name linstor-mgmt type vlan id 20
ip link set linstor-mgmt up
ip addr add 4.2.0.12/24 dev linstor-mgmt

# SETUP OVN NETWORK
ip link add link mlnx-bond name ovn-mgmt type vlan id 30
ip link set ovn-mgmt up
ip addr add 4.3.0.12/24 dev ovn-mgmt

# SETUP INCUS NETWORK
ip link add link mlnx-bond name incus-mgmt type vlan id 40
ip link set incus-mgmt up
ip addr add 4.4.0.12/24 dev incus-mgmt

# SETUP INCUS NETWORKS
ip link add link mlnx-bond name infra type vlan id 50
ip link set infra up

ip link add link mlnx-bond name admin-labs type vlan id 60
ip link set admin-labs up

ip link add link mlnx-bond name bdebruhl type vlan id 70
ip link set bdebruhl up

ip link add link mlnx-bond name bahartma type vlan id 80
ip link set bahartma up

ip link add link mlnx-bond name srbeard type vlan id 90
ip link set srbeard up

ip link add link mlnx-bond name dofang type vlan id 100
ip link set dofang up
