#!/usr/bin/env bash

set -Eeuo pipefail

hostname="$(hostname -s)"

modprobe tcp_bbr

io_policy() {
    for i in $(seq 0 20); do
        echo "round-robin" > /sys/class/nvme-subsystem/nvme-subsys"$i"/iopolicy
    done
}

network_r730xd1() {
    sysctl -w net.core.rmem_max=536870912

    sysctl -w net.core.wmem_max=536870912
    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=1540875
    sysctl -w fs.aio-max-nr=524288
    sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
    sysctl -w net.ipv6.neigh.default.gc_thresh3=8192
    sysctl -w vm.max_map_count=1048576

    # Unload bonding module 
    modprobe -r bonding || true

    # SETUP MTU
    modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
    ip link  add mlnx-bond type bond
    ip link  set enp132s0 down
    ip link set enp132s0d1 down
    ip link  set enp132s0 master mlnx-bond
    ip link  set enp132s0d1 master mlnx-bond
    ip link  set mlnx-bond up
    ip link set enp132s0 mtu 9000
    ip link set enp132s0d1 mtu 9000
    ip link set mlnx-bond mtu 9000

    # SETUP DRBD-RDMA REPLICATION
    ip link add link mlnx-bond name keepalived type vlan id 5
    ip link set keepalived up
    ip addr add 4.0.0.7/24 dev keepalived

    # SETUP DRBD REPLICATION
    ip link add link mlnx-bond name drbd type vlan id 10 
    ip link set drbd mtu 9000
    ip link set drbd up
    ip addr add 4.1.0.7/24 dev drbd

    # SETUP LINSTOR MGMT 
    ip link add link mlnx-bond name linstor-mgmt type vlan id 20
    ip link set linstor-mgmt mtu 9000
    ip link set linstor-mgmt up
    ip addr add 4.2.0.7/24 dev linstor-mgmt

    # SETUP OVN NETWORK
    ip link add link mlnx-bond name ovn-mgmt type vlan id 30
    ip link set ovn-mgmt mtu 9000
    ip link set ovn-mgmt up
    ip addr add 4.3.0.7/24 dev ovn-mgmt

    ip link set enp132s0 txqueuelen 10000
    ip link set enp132s0d1 txqueuelen 10000
    ip link set mlnx-bond txqueuelen 10000
    ip link set ovn-mgmt txqueuelen 10000
    ip link set linstor-mgmt txqueuelen 10000
    ip link set drbd txqueuelen 10000
}


network_r730xd2() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=1540875
    sysctl -w fs.aio-max-nr=524288
    sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
    sysctl -w net.ipv6.neigh.default.gc_thresh3=8192
    sysctl -w vm.max_map_count=1048576

    # Unload bonding module 
    modprobe -r bonding || true

    # SETUP MTU
    modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
    ip link  add mlnx-bond type bond
    ip link  set enp131s0 down
    ip link  set enp131s0 master mlnx-bond
    ip link  set enp131s0d1 master mlnx-bond
    ip link  set mlnx-bond up
    ip link set enp131s0 mtu 9000
    ip link set enp131s0d1 mtu 9000
    ip link set mlnx-bond mtu 9000


    # SETUP DRBD-RDMA REPLICATION
    ip link add link mlnx-bond name keepalived type vlan id 5
    ip link set keepalived up
    ip addr add 4.0.0.8/24 dev keepalived

    # SETUP DRBD REPLICATION
    ip link add link mlnx-bond name drbd type vlan id 10 
    ip link set drbd mtu 9000
    ip link set drbd up
    ip addr add 4.1.0.8/24 dev drbd

    # SETUP LINSTOR MGMT 
    ip link add link mlnx-bond name linstor-mgmt type vlan id 20
    ip link set linstor-mgmt mtu 9000
    ip link set linstor-mgmt up
    ip addr add 4.2.0.8/24 dev linstor-mgmt

    # SETUP OVN NETWORK
    ip link add link mlnx-bond name ovn-mgmt type vlan id 30
    ip link set ovn-mgmt mtu 9000
    ip link set ovn-mgmt up
    ip addr add 4.3.0.8/24 dev ovn-mgmt

    ip link set enp131s0 txqueuelen 10000
    ip link set enp131s0d1 txqueuelen 10000
    ip link set mlnx-bond txqueuelen 10000
    ip link set ovn-mgmt txqueuelen 10000
    ip link set linstor-mgmt txqueuelen 10000
    ip link set drbd txqueuelen 10000
}

network_r730xd3() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w fs.aio-max-nr=524288
    sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
    sysctl -w net.ipv6.neigh.default.gc_thresh3=8192
    sysctl -w vm.max_map_count=1048576

    # Set PFC through dcb
    #dcb pfc set dev enp131s0 prio-pfc all:off 3:on

    # Unload bonding module 
    # modprobe -r bonding || true

    # SETUP MTU
    #modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
    #ip link  add mlnx-bond type bond
    #ip link  set enp131s0 down
    #ip link  set enp131s0d1 down
    #ip link  set enp131s0 master mlnx-bond
    #ip link  set enp131s0d1 master mlnx-bond
    #ip link  set mlnx-bond up
    ip link set enp131s0 mtu 9000
    ip link set enp131s0d1 mtu 9000
    #ip link set mlnx-bond mtu 9000

    # SETUP DRBD REPLICATION
    ip link add link enp131s0d1 name keepalived type vlan id 5
    ip link set keepalived up
    ip addr add 4.0.0.9/24 dev keepalived

    # SETUP DRBD REPLICATION
    ip link add link enp131s0 name drbd type vlan id 10 
    ip link set drbd mtu 9000
    ip link set drbd up
    ip addr add 4.1.0.9/24 dev drbd

    # SETUP LINSTOR MGMT 
    ip link add link enp131s0d1 name linstor-mgmt type vlan id 20
    ip link set linstor-mgmt mtu 9000
    ip link set linstor-mgmt up
    ip addr add 4.2.0.9/24 dev linstor-mgmt

    # SETUP OVN NETWORK
    ip link add link enp131s0d1 name ovn-mgmt type vlan id 30
    ip link set ovn-mgmt mtu 9000
    ip link set ovn-mgmt up
    ip addr add 4.3.0.9/24 dev ovn-mgmt

    #ip link set enp131s0 txqueuelen 10000
    ip link set enp131s0d1 txqueuelen 10000
    #ip link set mlnx-bond txqueuelen 10000
    ip link set ovn-mgmt txqueuelen 10000
    ip link set linstor-mgmt txqueuelen 10000
    #ip link set drbd txqueuelen 10000

}

network_supermicro() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w vm.max_map_count=1048576

    # Unload bonding module 
    modprobe -r bonding || true

    # SETUP MTU
    modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
    ip link  add mlnx-bond type bond
    ip link  set enp175s0 down
    ip link  set enp175s0d1 down
    ip link  set enp175s0 master mlnx-bond
    ip link  set enp175s0d1 master mlnx-bond
    ip link  set mlnx-bond up
    ip link set enp175s0 mtu 9000
    ip link set enp175s0d1 mtu 9000
    ip link set mlnx-bond mtu 9000

    # KEEPALIVED MGMT
    ip link add link mlnx-bond name keepalived type vlan id 5
    ip link set keepalived up
    ip addr add 4.0.0.10/24 dev keepalived 

    # SETUP DRBD REPLICATION
    ip link add link mlnx-bond name drbd type vlan id 10
    ip link set drbd mtu 9000
    ip link set drbd up
    ip addr add 4.1.0.10/24 dev drbd

    # SETUP LINSTOR MGMT 
    ip link add link mlnx-bond name linstor-mgmt type vlan id 20
    ip link set linstor-mgmt mtu 9000
    ip link set linstor-mgmt up
    ip addr add 4.2.0.10/24 dev linstor-mgmt

    # SETUP OVN NETWORK
    ip link add link mlnx-bond name ovn-mgmt type vlan id 30
    ip link set ovn-mgmt mtu 9000
    ip link set ovn-mgmt up
    ip addr add 4.3.0.10/24 dev ovn-mgmt

    # SETUP INCUS NETWORK
    ip link add link mlnx-bond name incus-mgmt type vlan id 40
    ip link set incus-mgmt mtu 9000
    ip link set incus-mgmt up
    ip addr add 4.4.0.10/24 dev incus-mgmt

    # SETUP INCUS NETWORKS
    ip link add link mlnx-bond name infra type vlan id 50
    ip link set infra mtu 9000
    ip link set infra up 

    ip link add link mlnx-bond name admin-labs type vlan id 60
    ip link set admin-labs mtu 9000
    ip link set admin-labs up 

    ip link add link mlnx-bond name bdebruhl type vlan id 70
    ip link set bdebruhl mtu 9000
    ip link set bdebruhl up 

    ip link add link mlnx-bond name bhartma type vlan id 80
    ip link set bhartma mtu 9000
    ip link set bhartma up 

    ip link add link mlnx-bond name sbeard type vlan id 90
    ip link set sbeard mtu 9000
    ip link set sbeard up 

    ip link add link mlnx-bond name dofang type vlan id 100
    ip link set dofang mtu 9000
    ip link set dofang up      

    ip link set enp175s0 txqueuelen 10000
    ip link set enp175s0d1 txqueuelen 10000
    ip link set mlnx-bond txqueuelen 10000
    ip link set incus-mgmt txqueuelen 10000
    ip link set ovn-mgmt txqueuelen 10000
    ip link set linstor-mgmt txqueuelen 10000
    ip link set drbd txqueuelen 10000
    ip link set infra txqueuelen 10000 
    ip link set admin-labs txqueuelen 10000
    ip link set bdebruhl txqueuelen 10000
    ip link set bhartma txqueuelen 10000
    ip link set sbeard txqueuelen 10000
    ip link set dofang txqueuelen 10000
}

network_gigabyte() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w vm.max_map_count=1048576

    # Unload bonding module 
    modprobe -r bonding || true

    modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
    ip link add mlnx-bond type bond 

    ip link set enp65s0f0np0 down
    ip link set enp65s0f1np1 down

    ip link set enp65s0f0np0 master mlnx-bond
    ip link set enp65s0f1np1 master mlnx-bond

    ip link set enp65s0f0np0 up
    ip link set enp65s0f1np1 up
    ip link set mlnx-bond up
    ip link set enp65s0f0np0 mtu 9000
    ip link set enp65s0f1np1 mtu 9000
    ip link set mlnx-bond mtu 9000

    # KEEPALIVED MGMT
    ip link add link mlnx-bond name keepalived type vlan id 5
    ip link set keepalived up
    ip addr add 4.0.0.11/24 dev keepalived 

    ip link add link mlnx-bond name drbd type vlan id 10 
    ip link set drbd mtu 9000
    ip link set drbd up 
    ip addr add 4.1.0.11/24 dev drbd 

    ip link add link mlnx-bond name linstor-mgmt type vlan id 20 
    ip link set linstor-mgmt mtu 9000
    ip link set linstor-mgmt up
    ip addr add 4.2.0.11/24 dev linstor-mgmt 

    ip link add link mlnx-bond name ovn-mgmt type vlan id 30 
    ip link set ovn-mgmt mtu 9000
    ip link set ovn-mgmt up 
    ip addr add 4.3.0.11/24 dev ovn-mgmt 

    ip link add link mlnx-bond name incus-mgmt type vlan id 40
    ip link set incus-mgmt mtu 9000
    ip link set incus-mgmt up 
    ip addr add 4.4.0.11/24 dev incus-mgmt 

    ip link add link mlnx-bond name infra type vlan id 50 
    ip link set infra mtu 9000
    ip link set infra up  

    ip link add link mlnx-bond name admin-labs type vlan id 60 
    ip link set admin-labs mtu 9000
    ip link set admin-labs up 

    ip link add link mlnx-bond name bdebruhl type vlan id 70  
    ip link set bdebruhl mtu 9000
    ip link set bdebruhl up 

    ip link add link mlnx-bond name bhartma type vlan id 80 
    ip link set bhartma mtu 9000
    ip link set bhartma up 

    ip link add link mlnx-bond name sbeard type vlan id 90 
    ip link set sbeard mtu 9000
    ip link set sbeard up 

    ip link add link mlnx-bond name dofang type vlan id 100 
    ip link set dofang mtu 9000
    ip link set dofang up      


    ip link set enp65s0f0np0 txqueuelen 10000
    ip link set enp65s0f1np1 txqueuelen 10000
    ip link set mlnx-bond txqueuelen 10000
    ip link set incus-mgmt txqueuelen 10000
    ip link set ovn-mgmt txqueuelen 10000
    ip link set linstor-mgmt txqueuelen 10000
    ip link set drbd txqueuelen 10000
    ip link set infra txqueuelen 10000 
    ip link set admin-labs txqueuelen 10000
    ip link set bdebruhl txqueuelen 10000
    ip link set bhartma txqueuelen 10000
    ip link set sbeard txqueuelen 10000
    ip link set dofang txqueuelen 10000
    
}

network_r620() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w vm.max_map_count=1048576

    # Unload bonding module 
    modprobe -r bonding || true

    # SETUP MTU
    modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
    ip link add mlnx-bond type bond
    ip link set enp65s0 down
    ip link set enp66s0 down
    ip link set enp65s0 master mlnx-bond
    ip link set enp66s0 master mlnx-bond
    ip link set mlnx-bond up
    ip link set enp65s0 mtu 9000
    ip link set enp66s0 mtu 9000
    ip link set mlnx-bond mtu 9000

    # KEEPALIVED MGMT
    ip link add link mlnx-bond name keepalived type vlan id 5
    ip link set keepalived up
    ip addr add 4.0.0.12/24 dev keepalived 

    # SETUP DRBD REPLICATION
    ip link add link mlnx-bond name drbd type vlan id 10
    ip link set drbd mtu 9000
    ip link set drbd up
    ip addr add 4.1.0.12/24 dev drbd

    # SETUP LINSTOR MGMT 
    ip link add link mlnx-bond name linstor-mgmt type vlan id 20
    ip link set linstor-mgmt mtu 9000
    ip link set linstor-mgmt up
    ip addr add 4.2.0.12/24 dev linstor-mgmt

    # SETUP OVN NETWORK
    ip link add link mlnx-bond name ovn-mgmt type vlan id 30
    ip link set ovn-mgmt mtu 9000
    ip link set ovn-mgmt up
    ip addr add 4.3.0.12/24 dev ovn-mgmt

    # SETUP INCUS NETWORK
    ip link add link mlnx-bond name incus-mgmt type vlan id 40
    ip link set incus-mgmt mtu 9000
    ip link set incus-mgmt up
    ip addr add 4.4.0.12/24 dev incus-mgmt

    # SETUP INCUS NETWORKS
    ip link add link mlnx-bond name infra type vlan id 50
    ip link set infra mtu 9000
    ip link set infra up 

    ip link add link mlnx-bond name admin-labs type vlan id 60
    ip link set admin-labs mtu 9000
    ip link set admin-labs up 

    ip link add link mlnx-bond name bdebruhl type vlan id 70
    ip link set bdebruhl mtu 9000
    ip link set bdebruhl up 

    ip link add link mlnx-bond name bhartma type vlan id 80
    ip link set bhartma mtu 9000
    ip link set bhartma up 

    ip link add link mlnx-bond name sbeard type vlan id 90
    ip link set sbeard mtu 9000
    ip link set sbeard up 

    ip link add link mlnx-bond name dofang type vlan id 100
    ip link set dofang mtu 9000
    ip link set dofang up      

    ip link set enp66s0 txqueuelen 10000
    ip link set enp65s0 txqueuelen 10000
    ip link set mlnx-bond txqueuelen 10000
    ip link set incus-mgmt txqueuelen 10000
    ip link set ovn-mgmt txqueuelen 10000
    ip link set linstor-mgmt txqueuelen 10000
    ip link set drbd txqueuelen 10000
    ip link set infra txqueuelen 10000 
    ip link set admin-labs txqueuelen 10000
    ip link set bdebruhl txqueuelen 10000
    ip link set bhartma txqueuelen 10000
    ip link set sbeard txqueuelen 10000
    ip link set dofang txqueuelen 10000
}

cpu_performance() {
    cpupower -c all  frequency-set --governor performance
}

if [[ "$hostname" == "gigabyte" ]]; then
    cpu_performance

    ethtool -K enp65s0f0np0 rx on 
    ethtool -K enp65s0f0np0 tx on 
    ethtool -K enp65s0f0np0 sg on 
    ethtool -K enp65s0f0np0 tso on 
    ethtool -K enp65s0f0np0 gso on 
    ethtool -K enp65s0f0np0 gro on 
    ethtool -K enp65s0f0np0 rxvlan on 
    ethtool -K enp65s0f0np0 txvlan on 
    ethtool -K enp65s0f0np0 rxhash on 
    ethtool -K enp65s0f0np0 hw-tc-offload on
    ethtool -K enp65s0f0np0 rx-udp-gro-forwarding on
    ethtool -K enp65s0f0np0 rx-gro-list on
    ethtool -K enp65s0f0np0 rx-all off
    ethtool -G enp65s0f1np1 rx 8192 tx 8192
    
    ethtool -K enp65s0f1np1 rx on 
    ethtool -K enp65s0f1np1 tx on 
    ethtool -K enp65s0f1np1 sg on 
    ethtool -K enp65s0f1np1 tso on 
    ethtool -K enp65s0f1np1 gso on 
    ethtool -K enp65s0f1np1 gro on 
    ethtool -K enp65s0f1np1 rxvlan on 
    ethtool -K enp65s0f1np1 txvlan on 
    ethtool -K enp65s0f1np1 rxhash on 
    ethtool -K enp65s0f1np1 hw-tc-offload on
    ethtool -K enp65s0f0np0 rx-udp-gro-forwarding on
    ethtool -K enp65s0f0np0 rx-gro-list on
    ethtool -K enp65s0f0np0 rx-all off

    ethtool -G enp65s0f0np0   rx 8192 tx 8192


    ethtool -C enp65s0f0np0 adaptive-rx on adaptive-tx on
    ethtool -C enp65s0f1np1 adaptive-rx on adaptive-tx on

    network_gigabyte
    io_policy

elif [ "$hostname" == "supermicro" ]; then
    cpu_performance
    ethtool -K enp175s0    rx on 
    ethtool -K enp175s0    tx on 
    ethtool -K enp175s0    sg on 
    ethtool -K enp175s0    tso on 
    ethtool -K enp175s0    gso on 
    ethtool -K enp175s0    gro on 
    ethtool -K enp175s0    rxvlan on 
    ethtool -K enp175s0    txvlan on 
    ethtool -K enp175s0    rxhash on

    ethtool -G enp175s0   rx 8192 tx 8192

    ethtool -K enp175s0d1    rx on 
    ethtool -K enp175s0d1    tx on 
    ethtool -K enp175s0d1    sg on 
    ethtool -K enp175s0d1    tso on 
    ethtool -K enp175s0d1    gso on 
    ethtool -K enp175s0d1    gro on 
    ethtool -K enp175s0d1    rxvlan on 
    ethtool -K enp175s0d1    txvlan on 
    ethtool -K enp175s0d1    rxhash on

    ethtool -G enp175s0d1   rx 8192 tx 8192

    network_supermicro
    io_policy

elif [ "$hostname" == "r620" ]; then
    cpu_performance
    ethtool -K enp65s0    rx on 
    ethtool -K enp65s0    tx on 
    ethtool -K enp65s0    sg on 
    ethtool -K enp65s0    tso on 
    ethtool -K enp65s0    gso on 
    ethtool -K enp65s0    gro on 
    ethtool -K enp65s0    rxvlan on 
    ethtool -K enp65s0    txvlan on 
    ethtool -K enp65s0    rxhash on
    ethtool -G enp65s0   rx 8192 tx 8192

    ethtool -K enp66s0    rx on 
    ethtool -K enp66s0    tx on 
    ethtool -K enp66s0    sg on 
    ethtool -K enp66s0    tso on 
    ethtool -K enp66s0    gso on 
    ethtool -K enp66s0    gro on 
    ethtool -K enp66s0    rxvlan on 
    ethtool -K enp66s0    txvlan on 
    ethtool -K enp66s0    rxhash on

    ethtool -G enp66s0   rx 8192 tx 8192

    network_r620
    io_policy
    
elif [ "$hostname" == "r730xd-1" ]; then
    cpu_performance
    ethtool -K enp132s0 rx on 
    ethtool -K enp132s0    tx on 
    ethtool -K enp132s0    sg on 
    ethtool -K enp132s0    tso on 
    ethtool -K enp132s0    gso on 
    ethtool -K enp132s0    gro on 
    ethtool -K enp132s0    rxvlan on 
    ethtool -K enp132s0    txvlan on 
    ethtool -K enp132s0    rxhash on

    ethtool -G enp132s0   rx 8192 tx 8192

    ethtool -K enp132s0d1 rx on 
    ethtool -K enp132s0d1    tx on 
    ethtool -K enp132s0d1    sg on 
    ethtool -K enp132s0d1    tso on 
    ethtool -K enp132s0d1    gso on 
    ethtool -K enp132s0d1    gro on 
    ethtool -K enp132s0d1    rxvlan on 
    ethtool -K enp132s0d1    txvlan on 
    ethtool -K enp132s0d1    rxhash on

    ethtool -G enp132s0d1   rx 8192 tx 8192

    network_r730xd1
    io_policy

elif [ "$hostname" == "r730xd-2" ]; then
    cpu_performance
    ethtool -K enp131s0    rx on 
    ethtool -K enp131s0    tx on 
    ethtool -K enp131s0   sg on 
    ethtool -K enp131s0    tso on 
    ethtool -K enp131s0    gso on 
    ethtool -K enp131s0    gro on 
    ethtool -K enp131s0    rxvlan on 
    ethtool -K enp131s0    txvlan on 
    ethtool -K enp131s0    rxhash on

    ethtool -G enp131s0   rx 8192 tx 8192

    ethtool -K enp131s0d1    rx on 
    ethtool -K enp131s0d1    tx on 
    ethtool -K enp131s0d1    sg on 
    ethtool -K enp131s0d1   tso on 
    ethtool -K enp131s0d1   gso on 
    ethtool -K enp131s0d1   gro on 
    ethtool -K enp131s0d1   rxvlan on 
    ethtool -K enp131s0d1   txvlan on 
    ethtool -K enp131s0d1   rxhash on

    ethtool -G enp131s0d1   rx 8192 tx 8192

    network_r730xd2
    io_policy

elif [ "$hostname" == "r730xd-3" ]; then
    cpu_performance
    ethtool -K enp131s0    rx on 
    ethtool -K enp131s0    tx on 
    ethtool -K enp131s0    sg on 
    ethtool -K enp131s0    tso on 
    ethtool -K enp131s0    gso on 
    ethtool -K enp131s0    gro on 
    ethtool -K enp131s0    rxvlan on 
    ethtool -K enp131s0    txvlan on 
    ethtool -K enp131s0    rxhash on

    ethtool -G enp131s0   rx 8192 tx 8192

    ethtool -K enp131s0d1    rx on 
    ethtool -K enp131s0d1    tx on 
    ethtool -K enp131s0d1    sg on 
    ethtool -K enp131s0d1    tso on 
    ethtool -K enp131s0d1    gso on 
    ethtool -K enp131s0d1    gro on 
    ethtool -K enp131s0d1    rxvlan on 
    ethtool -K enp131s0d1    txvlan on 
    ethtool -K enp131s0d1    rxhash on

    ethtool -G enp131s0    rx 8192 tx 8192

    network_r730xd3
    io_policy
else
    echo "Hostname does not match."
fi
