#!/usr/bin/env bash

set -Eeuo pipefail

hostname="$(hostname -s)"

modprobe tcp_bbr

network_r730xd1() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
    sysctl -w net.ipv4.tcp_window_scaling=1
    sysctl -w net.core.wmem_max=536870912
    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w fs.aio-max-nr=524288
    sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
    sysctl -w net.ipv6.neigh.default.gc_thresh3=8192
    sysctl -w vm.max_map_count=1048576

    curl -sSL https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r730xd-1/network_infra | sudo bash
}


network_r730xd2() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
    sysctl -w net.ipv4.tcp_window_scaling=1

    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w fs.aio-max-nr=524288
    sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
    sysctl -w net.ipv6.neigh.default.gc_thresh3=8192
    sysctl -w vm.max_map_count=1048576

    curl -sSL https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r730xd-2/network_infra | sudo bash
}

network_r730xd3() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
    sysctl -w net.ipv4.tcp_window_scaling=1
    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w fs.aio-max-nr=524288
    sysctl -w net.ipv4.neigh.default.gc_thresh3=8192
    sysctl -w net.ipv6.neigh.default.gc_thresh3=8192
    sysctl -w vm.max_map_count=1048576

    curl -sSL https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r730xd-3/network_infra | sudo bash
}

network_supermicro() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
    sysctl -w net.ipv4.tcp_window_scaling=1
    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w vm.max_map_count=1048576

    curl -sSL https://github.com/mgherghi/CalPoly_Infrastructure/blob/main/supermicro/network_infra | sudo bash


}

network_gigabyte() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
    sysctl -w net.ipv4.tcp_window_scaling=1
    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w vm.max_map_count=1048576

    curl -sSL https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/gigabyte/network_infra | sudo bash

}

network_r620() {
    sysctl -w net.core.rmem_max=536870912
    sysctl -w net.core.wmem_max=536870912

    sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
    sysctl -w net.ipv4.tcp_window_scaling=1
    sysctl -w net.ipv4.tcp_rmem="4096 87380 268435456"
    sysctl -w net.ipv4.tcp_wmem="4096 65536 268435456"
    sysctl -w net.ipv4.tcp_mtu_probing=1
    sysctl -w net.core.default_qdisc=fq
    sysctl -w net.ipv4.tcp_congestion_control=bbr
    sysctl -w net.core.netdev_max_backlog=65536
    sysctl -w vm.max_map_count=1048576

    curl -sSL https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r620/network_infra | sudo bash

}

cpu_performance() {
    cpupower -c all  frequency-set --governor performance
}

if [[ "$hostname" == "gigabyte" ]]; then
    cpu_performance

    ethtool -K enp65s0f0np0 rx on 
    ethtool -K enp65s0f0np0 tx on 
    ethtool -K enp65s0f0np0 sg on 
    ethtool -K enp65s0f0np0 tso on 
    ethtool -K enp65s0f0np0 gso on 
    ethtool -K enp65s0f0np0 gro on 
    ethtool -K enp65s0f0np0 rxvlan on 
    ethtool -K enp65s0f0np0 txvlan on 
    ethtool -K enp65s0f0np0 rxhash on 
    ethtool -K enp65s0f0np0 hw-tc-offload on
    ethtool -K enp65s0f0np0 rx-udp-gro-forwarding on
    ethtool -K enp65s0f0np0 rx-gro-list on
    ethtool -K enp65s0f0np0 rx-all off
    #ethtool -G enp65s0f1np1 rx 8192 tx 8192
    
    ethtool -K enp65s0f1np1 rx on 
    ethtool -K enp65s0f1np1 tx on 
    ethtool -K enp65s0f1np1 sg on 
    ethtool -K enp65s0f1np1 tso on 
    ethtool -K enp65s0f1np1 gso on 
    ethtool -K enp65s0f1np1 gro on 
    ethtool -K enp65s0f1np1 rxvlan on 
    ethtool -K enp65s0f1np1 txvlan on 
    ethtool -K enp65s0f1np1 rxhash on 
    ethtool -K enp65s0f1np1 hw-tc-offload on
    ethtool -K enp65s0f0np0 rx-udp-gro-forwarding on
    ethtool -K enp65s0f0np0 rx-gro-list on
    ethtool -K enp65s0f0np0 rx-all off

    #ethtool -G enp65s0f0np0   rx 8192 tx 8192


    ethtool -C enp65s0f0np0 adaptive-rx on adaptive-tx on
    ethtool -C enp65s0f1np1 adaptive-rx on adaptive-tx on

    network_gigabyte
    #/usr/sbin/toggle_gpu vm

elif [ "$hostname" == "supermicro" ]; then
    cpu_performance
    ethtool -K enp175s0    rx on 
    ethtool -K enp175s0    tx on 
    ethtool -K enp175s0    sg on 
    ethtool -K enp175s0    tso on 
    ethtool -K enp175s0    gso on 
    ethtool -K enp175s0    gro on 
    ethtool -K enp175s0    rxvlan on 
    ethtool -K enp175s0    txvlan on 
    ethtool -K enp175s0    rxhash on

    #ethtool -G enp175s0   rx 8192 tx 8192

    ethtool -K enp175s0d1    rx on 
    ethtool -K enp175s0d1    tx on 
    ethtool -K enp175s0d1    sg on 
    ethtool -K enp175s0d1    tso on 
    ethtool -K enp175s0d1    gso on 
    ethtool -K enp175s0d1    gro on 
    ethtool -K enp175s0d1    rxvlan on 
    ethtool -K enp175s0d1    txvlan on 
    ethtool -K enp175s0d1    rxhash on

    #ethtool -G enp175s0d1   rx 8192 tx 8192

    network_supermicro
    #/usr/sbin/toggle_gpu vm
    

elif [ "$hostname" == "r620" ]; then
    cpu_performance
    ethtool -K enp65s0    rx on 
    ethtool -K enp65s0    tx on 
    ethtool -K enp65s0    sg on 
    ethtool -K enp65s0    tso on 
    ethtool -K enp65s0    gso on 
    ethtool -K enp65s0    gro on 
    ethtool -K enp65s0    rxvlan on 
    ethtool -K enp65s0    txvlan on 
    ethtool -K enp65s0    rxhash on
    
    #ethtool -G enp65s0   rx 8192 tx 8192

    ethtool -K enp66s0    rx on 
    ethtool -K enp66s0    tx on 
    ethtool -K enp66s0    sg on 
    ethtool -K enp66s0    tso on 
    ethtool -K enp66s0    gso on 
    ethtool -K enp66s0    gro on 
    ethtool -K enp66s0    rxvlan on 
    ethtool -K enp66s0    txvlan on 
    ethtool -K enp66s0    rxhash on

    #ethtool -G enp66s0   rx 8192 tx 8192

    network_r620
    
    
elif [ "$hostname" == "r730xd-1" ]; then
    cpu_performance
    ethtool -K enp140s0    rx on 
    ethtool -K enp140s0    tx on 
    ethtool -K enp140s0    sg on 
    ethtool -K enp140s0    tso on 
    ethtool -K enp140s0    gso on 
    ethtool -K enp140s0    gro on 
    ethtool -K enp140s0    rxvlan on 
    ethtool -K enp140s0    txvlan on 
    ethtool -K enp140s0    rxhash on

    #ethtool -G enp140s0   rx 8192 tx 8192

    ethtool -K enp140s0d1    rx on 
    ethtool -K enp140s0d1    tx on 
    ethtool -K enp140s0d1    sg on 
    ethtool -K enp140s0d1    tso on 
    ethtool -K enp140s0d1    gso on 
    ethtool -K enp140s0d1    gro on 
    ethtool -K enp140s0d1    rxvlan on 
    ethtool -K enp140s0d1    txvlan on 
    ethtool -K enp140s0d1    rxhash on

    #ethtool -G enp140s0d1   rx 8192 tx 8192

    network_r730xd1

elif [ "$hostname" == "r730xd-2" ]; then
    cpu_performance
    ethtool -K enp139s0    rx on 
    ethtool -K enp139s0    tx on 
    ethtool -K enp139s0   sg on 
    ethtool -K enp139s0    tso on 
    ethtool -K enp139s0    gso on 
    ethtool -K enp139s0    gro on 
    ethtool -K enp139s0    rxvlan on 
    ethtool -K enp139s0    txvlan on 
    ethtool -K enp139s0    rxhash on

    #ethtool -G enp131s0   rx 8192 tx 8192

    ethtool -K enp139s0d1    rx on 
    ethtool -K enp139s0d1    tx on 
    ethtool -K enp139s0d1    sg on 
    ethtool -K enp139s0d1   tso on 
    ethtool -K enp139s0d1   gso on 
    ethtool -K enp139s0d1   gro on 
    ethtool -K enp139s0d1   rxvlan on 
    ethtool -K enp139s0d1   txvlan on 
    ethtool -K enp139s0d1   rxhash on

    #ethtool -G enp139s0d1   rx 8192 tx 8192

    network_r730xd2
    

elif [ "$hostname" == "r730xd-3" ]; then
    cpu_performance
    ethtool -K enp139s0    rx on 
    ethtool -K enp139s0    tx on 
    ethtool -K enp139s0    sg on 
    ethtool -K enp139s0    tso on 
    ethtool -K enp139s0    gso on 
    ethtool -K enp139s0    gro on 
    ethtool -K enp139s0    rxvlan on 
    ethtool -K enp139s0    txvlan on 
    ethtool -K enp139s0    rxhash on

    #ethtool -G enp139s0   rx 8192 tx 8192

    ethtool -K enp139s0d1    rx on 
    ethtool -K enp139s0d1    tx on 
    ethtool -K enp139s0d1    sg on 
    ethtool -K enp139s0d1    tso on 
    ethtool -K enp139s0d1    gso on 
    ethtool -K enp139s0d1    gro on 
    ethtool -K enp139s0d1    rxvlan on 
    ethtool -K enp139s0d1    txvlan on 
    ethtool -K enp139s0d1    rxhash on

    #ethtool -G enp139s0d1    rx 8192 tx 8192

    network_r730xd3
    
else
    echo "Hostname does not match."
fi
