#!/bin/bash

hostname=$(hostname)

# SETUP LINSTOR KEY
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linbit.asc -O /etc/apt/keyrings/linbit.asc && wait

# SETUP LINSTOR REPO
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linstor.sources -O /etc/apt/sources.list.d/linstor.sources && wait

# CREATE BOOT FOLDERS
mkdir -p /home/.essentials
mkdir -p /home/.essentials/startup 

# GET NETWORK BOOTUP SCRIPT
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/network -O /home/.essentials/startup/network && wait

# SETUP OF PERFORMANCE GOVERNER
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/cpupower -O /home/.essentials/startup/cpupower && wait

# SETUP OF BOOT SCRIPT
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/bootscript -O /home/.essentials/boot_script && wait

chmod u+x /home/.essentials/boot_script && wait

echo "post-up /home/.essentials/boot_script" >> /etc/network/interfaces  && wait

apt update && apt install avahi-daemon linux-cpupower nvme-cli lvm2 firmware-linux -y  && wait

hostname=$(hostname)

if [[ "$hostname" == "r730xd-1" ]]; then

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.7 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.7 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.7 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.7 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

elif [[ "$hostname" == "r730xd-2" ]]; then

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.8 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.8 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.8 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.8 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait  

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

elif [[ "$hostname" == "r730xd-3" ]]; then

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.9 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.9 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.9 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.9 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait 

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

elif [[ "$hostname" == "supermicro" ]]; then

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.6 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.6 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.6 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.6 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

elif [[ "$hostname" == "r620" ]]; then

#VF's for NiC
  apt install rdma-core
  echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12" >> /etc/modprobe.d/mlx4.conf
  update-initramfs -c -u -k all


# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.10 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.10 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.10 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.10 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
  update-grub
  systemctl reboot

elif [[ "$hostname" == "r720-1" ]]; then

#VF's for NiC
  apt install rdma-core -y 
  echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12"  >> /etc/modprobe.d/mlx4.conf
  update-initramfs -c -u -k all

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.11 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.11 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.11 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.11 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
  update-grub
  systemctl reboot
elif [[ "$hostname" == "r720-2" ]]; then

#VF's for NiC
  apt install rdma-core -y 
  echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12"  >> /etc/modprobe.d/mlx4.conf
  update-initramfs -c -u -k all

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.12 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.12 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.12 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.12 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
  update-grub
  systemctl reboot
elif [[ "$hostname" == "r720-3" ]]; then

#VF's for NiC
  apt install rdma-core -y 
  echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12"  >> /etc/modprobe.d/mlx4.conf
  update-initramfs -c -u -k all

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.13 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.13 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.13 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.13 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
  update-grub
  systemctl reboot
else
  echo "Unknown host: $hostname"
fi

chmod u+x /home/.essentials/startup/* && wait
