#!/bin/bash

hostname=$(hostname)

# SETUP PATH
path_setup() {
    echo "export PATH=$PATH:/sbin" >> /home/mihai/.bashrc
    source /home/mihai/.bashrc
}


#SETUP INCUS REPO AND KEY FUNCTION
incus_setup() {
    # Create keyrings directory if missing

    echo "[*] Downloading Incus apt key..."
    wget -qO /etc/apt/keyrings/zabbly.asc https://pkgs.zabbly.com/key.asc

    echo "[*] Configuring Incus apt repository..."
    cat <<EOF | tee /etc/apt/sources.list.d/zabbly-incus-stable.sources >/dev/null
    Enabled: yes
    Types: deb
    URIs: https://pkgs.zabbly.com/incus/stable
    Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
    Components: main
    Architectures: $(dpkg --print-architecture)
    Signed-By: /etc/apt/keyrings/zabbly.asc
EOF


    echo "[*] Incus repo setup complete."
    apt update
}

# SETUP LINSTOR KEY AND REPO
linstor_setup() {
    wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linbit.asc -O /etc/apt/keyrings/linbit.asc && wait
    wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linstor.sources -O /etc/apt/sources.list.d/linstor.sources && wait
    apt update
    echo "[*] linstor repo setup complete."
}

# CREATE BOOT FOLDERS
mkdir -p /home/.essentials
mkdir -p /home/.essentials/startup

# GET NETWORK BOOTUP SCRIPT
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/network -O /home/.essentials/startup/network && wait

# SETUP OF PERFORMANCE GOVERNER
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/cpupower -O /home/.essentials/startup/cpupower && wait

# # SETUP OF BOOT SCRIPT
# wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/bootscript -O /home/.essentials/boot_script && wait

# SETUP BOOT SCRIPT
echo "post-up /home/.essentials/boot_script" >> /etc/network/interfaces  && wait

# DOWNLOAD TCP SYSCTL OPTIMIZATIONS
wget https://github.com/mgherghi/CalPoly_Infrastructure/blob/main/"$(hostname)"/10-tcp.conf -O /etc/sysctl.d/10-tcp.conf

# DOWNLOAD MLNX-PREP
wget https://github.com/mgherghi/CalPoly_Infrastructure/blob/main/"$(hostname)"/mlnx-prep -O /home/.essentials/startup/mlnx-prep && wait


# SETUP APP INSTALLS
apt_setup() {
    apt update && apt install ethtool vlan linstor-satellite ovn-host linux-cpupower linux-headers-amd64 linux-image-amd64 drbd-utils bcache-tools tini lvm2 zstd socat curl udev lsscsi nvme-cli cryptsetup thin-provisioning-tools thin-send-recv dkms drbd-dkms drbd-utils nvme-cli lvm2 firmware-linux -y  && wait
    echo "8021q" >> /etc/modules
    update-initramfs -u -k all
}

path_setup
linstor_setup
apt_setup

hostname=$(hostname)

if [[ "$hostname" == "r730xd-1" ]]; then


# Apt install for remaining stuff
  apt update -y && apt install ovn-central linstor-controller linstor-client python3-setuptools -y

# # FIX MDNS FOR EASY LOOKUP
#   echo "5.0.0.7 lan-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.0.7 ovs-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.1.7 linstor-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.2.7 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

# SAVE OVN-CENTRAL FILE TO HOST
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovn-central -O /etc/default/ovn-central

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

# CONFIGURE BOOT SCRIPT
  echo "/home/.essentials/startup/iopolicy" > /home/.essentials/boot_script
  echo "/home/.essentials/startup/cpupower" >> /home/.essentials/boot_script
  echo "/home/.essentials/startup/mlnx-prep" >> /home/.essentials/boot_script
  echo "/home/.essentials/startup/network" >> /home/.essentials/boot_script


elif [[ "$hostname" == "r730xd-2" ]]; then

# Apt install for remaining stuff
  apt update -y && apt install ovn-central

# FIX MDNS FOR EASY LOOKUP
#   echo "5.0.0.8 lan-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.0.8 ovs-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.1.8 linstor-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.2.8 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

# SAVE OVN-CENTRAL FILE TO HOST
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovn-central -O /etc/default/ovn-central

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

# CONFIGURE BOOT SCRIPT
  echo "/home/.essentials/startup/iopolicy" > /home/.essentials/boot_script
  echo "/home/.essentials/startup/cpupower" >> /home/.essentials/boot_script
  echo "/home/.essentials/startup/mlnx-prep" >> /home/.essentials/boot_script
  echo "/home/.essentials/startup/network" >> /home/.essentials/boot_script

elif [[ "$hostname" == "r730xd-3" ]]; then

# Remaning apt packages
  apt update -y && apt install ovn-central

# FIX MDNS FOR EASY LOOKUP
#   echo "5.0.0.9 lan-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.0.9 ovs-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.1.9 linstor-$(hostname).local" >> /etc/avahi/hosts
#   echo "4.0.2.9 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

# SAVE OVN-CENTRAL FILE TO HOST
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovn-central -O /etc/default/ovn-central

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

# CONFIGURE BOOT SCRIPT
  echo "/home/.essentials/startup/iopolicy" > /home/.essentials/boot_script
  echo "/home/.essentials/startup/cpupower" >> /home/.essentials/boot_script
  echo "/home/.essentials/startup/mlnx-prep" >> /home/.essentials/boot_script
  echo "/home/.essentials/startup/network" >> /home/.essentials/boot_script



elif [[ "$hostname" == "supermicro" ]]; then
  apt update -y && apt install linstor-satellite ovn-host 

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.10 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.10 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.10 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.10 incus-$(hostname).local" >> /etc/avahi/hosts

#  echo "/home/.essential/startup/iopolicy" >> /home/.essentials/boot_script

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

elif [[ "$hostname" == "r620" ]]; then

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.6 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.6 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.6 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.6 incus-$(hostname).local" >> /etc/avahi/hosts

#  sed -i '/iopolicy/d' /home/.essentials/boot_script

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

# RUN INCUS SETUP
  incus_setup

elif [[ "$hostname" == "gigabyte" ]]; then

# Setup Gigabyte
  apt update && apt upgrade -y && apt install linstor-satellite ovn-host 

# Setup SR-IOV  
  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on intel_iommu=on iommu=pt"@' /etc/default/grub
  update-grub

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.5 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.5 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.5 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.5 incus-$(hostname).local" >> /etc/avahi/hosts

# ALLOW MULTIPATH FOR NVME
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait  

# CHANGE IO POLICY ON NVME DRIVES
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

# GET MLNX PREP 
  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/gigabyte/mlnx_prep -O  /home/.essentials/startup/mlnx-prep
  echo "/home/.essentials/startup/mlnx-prep" >> /home/.essentials/boot_script

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

# RUN INCUS SETUP
  incus_setup

elif [[ "$hostname" == "r720-1" ]]; then

#VF's for NiC
#  apt install rdma-core -y 
#  echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12"  >> /etc/modprobe.d/mlx4.conf
#  update-initramfs -c -u -k all

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.11 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.11 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.11 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.11 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

#  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
#  update-grub
#  systemctl reboot
elif [[ "$hostname" == "r720-2" ]]; then

#VF's for NiC
 # apt install rdma-core -y 
 # echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12"  >> /etc/modprobe.d/mlx4.conf
 # update-initramfs -c -u -k all

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.12 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.12 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.12 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.12 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

#  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
#  update-grub
#  systemctl reboot
elif [[ "$hostname" == "r720-3" ]]; then

#VF's for NiC
#  apt install rdma-core -y 
#  echo "options mlx4_core log_num_mgm_entry_size=-1 num_vfs=12 port_type_array=2 probe_vf=12"  >> /etc/modprobe.d/mlx4.conf
#  update-initramfs -c -u -k all

# FIX MDNS FOR EASY LOOKUP
  echo "5.0.0.13 lan-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.0.13 ovs-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.1.13 linstor-$(hostname).local" >> /etc/avahi/hosts
  echo "4.0.2.13 incus-$(hostname).local" >> /etc/avahi/hosts

  sed -i '/iopolicy/d' /home/.essentials/boot_script

# RUN OVN-CENTRAL COMMAND
  wget -qO- https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/"$(hostname)"/ovs-command | bash

#  sed -i 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet"@GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"@' /etc/default/grub
#  update-grub
#  systemctl reboot
else
  echo "Unknown host: $hostname"
fi

chmod u+x /home/.essentials/startup/* && chmod -R u+x /home/.essentials/* && wait
