#!/bin/bash

# SETUP LINSTOR KEY
echo "Setting up Linstor"
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linbit.asc -O /etc/apt/keyrings/linbit.asc && wait

# SETUP LINSTOR REPO
echo "Setting up Linstor repo"
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linstor.sources -O /etc/apt/sources.list.d/linstor.sources && wait

# CREATE BOOT FOLDERS
echo "creating bootup folders"
mkdir -p /home/.essentials
mkdir -p /home/.essentials/startup 

# ALLOW MULTIPATH FOR NVME
echo "getting multipath config"
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/nvme_core.conf -O /etc/modprobe.d/nvme_core.conf && wait

# CHANGE IO POLICY ON NVME DRIVES
echo "getting iopolicy config"
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/iopolicy -O /home/.essentials/startup/iopolicy && wait

# SETUP OF PERFORMANCE GOVERNER
echo "setting up performance governer"
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/cpupower -O /home/.essentials/startup/cpupower && wait

# SETUP OF BOOT SCRIPT
echo "setting up bootscript"
wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/bootscript -O /home/.essentials/boot_script && wait

chmod u+x /home/.essentials/boot_script && wait

echo "post-up /home/.essentials/boot_script" >> /etc/network/interfaces  && wait

echo "installing apps"
apt update && apt install avahi-daemon linux-cpupower nvme-cli lvm2 firmware-linux -y  && wait


echo "fixing network configs"
hostname=$(hostname)

if [[ "$hostname" == "r730xd-1" ]]; then

  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r730xd-1/network -O /home/.essentials/startup/network && wait
  echo "5.0.0.7 lan-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.0.7 ovs-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.1.7 linstor-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.2.7 incus-$hostname.local" >> /etc/avahi/hosts

elif [[ "$hostname" == "r730xd-2" ]]; then

  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r730xd-2/network -O /home/.essentials/startup/network && wait
  echo "5.0.0.8 lan-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.0.8 ovs-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.1.8 linstor-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.2.8 incus-$hostname.local" >> /etc/avahi/hosts

elif [[ "$hostname" == "r730xd-3" ]]; then

  wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/r730xd-3/network -O /home/.essentials/startup/network && wait
  echo "5.0.0.9 lan-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.0.9 ovs-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.1.9 linstor-$hostname.local" >> /etc/avahi/hosts
  echo "4.0.2.9 incus-$hostname.local" >> /etc/avahi/hosts

else
  echo "Unknown host: $hostname"
fi

chmod u+x /home/.essentials/startup/* && wait
echo "ALL DONE !!"
