# ------------------------------------------------------------
# admin.calpolynglab.com
# ------------------------------------------------------------



map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "2.0.0.2";
  set $port           8089;

  listen 80;
listen [::]:80;

listen 443 ssl;
listen [::]:443 ssl;


  server_name admin.calpolynglab.com;

  http2 on;


  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-cache.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-16/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-16/privkey.pem;




# Asset Caching
  include conf.d/include/assets.conf;








    # Force SSL
    
    set $trust_forwarded_proto "F";
    
    include conf.d/include/force-ssl.conf;




proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;


  access_log /data/logs/proxy-host-8_access.log proxy;
  error_log /data/logs/proxy-host-8_error.log warn;

auth_request /oauth2/auth;
error_page 401 = @oauth2_signin;


location = /oauth2/auth {
    auth_request off;

    proxy_pass http://2.0.0.2:4180/oauth2/auth;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Uri $request_uri;
}


# EVERYTHING under /oauth2/ bypasses auth_request
location ^~ /oauth2/ {
    auth_request off;

    proxy_pass http://2.0.0.2:4180;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
}


location @oauth2_signin {
    auth_request off;

    return 302 /oauth2/start?rd=$scheme://$host$request_uri;
}





  location / {









    
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
    

    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

