FROM debian:13-slim

USER root
RUN apt update -y && apt install wget -y && wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linbit.asc -O /etc/apt/keyrings/linbit.asc && wait && wget https://raw.githubusercontent.com/mgherghi/CalPoly_Infrastructure/refs/heads/main/Infrastructure/linstor.sources -O /etc/apt/sources.list.d/linstor.sources && wait && apt update -y
RUN apt install drbd-utils bcache-tools tini lvm2 zstd socat curl udev lsscsi nvme-cli cryptsetup thin-provisioning-tools linstor-satellite  -y

# Fetch entrypoint with checksum verification
RUN set -eux; \
    curl -fsSL "$SCRIPT_URL" -o /usr/local/bin/docker-entrypoint-linstor-satellite.sh; \
    chmod +x /usr/local/bin/docker-entrypoint-linstor-satellite.sh

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/usr/local/bin/docker-entrypoint-linstor-satellite.sh"]
