server:
    # Listen on all interfaces
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow
    port: 53
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # Standard security protocols
    hide-identity: yes
    hide-version: yes

# Dynamically query Incus Node 1 for Project A records
stub-zone:
    name: "infra.guacd"
    stub-addr: 4.2.0.10@1053
    stub-addr: 4.2.0.11@1053  # High Availability cluster fallback
    stub-addr: 4.2.0.12@1053  # High Availability cluster fallback 

# Dynamically query Incus Node 1 for Project B records
stub-zone:
    name: "bdebruhl.testing"
    stub-addr: 4.2.0.10@1053
    stub-addr: 4.2.0.11@1053  # High Availability cluster fallback
    stub-addr: 4.2.0.12@1053  # High Availability cluster fallback
