#!/usr/bin/env bash
set -euo pipefail

echo "Detecting Mellanox CX6-DX Pro NICs ..."

for dev in /sys/bus/pci/devices/*; do
  # Mellanox vendor ID
  [[ "$(cat "$dev/vendor" 2>/dev/null)" != "0x15b3" ]] && continue

  # CX3 Pro uses mlx4 driver
  [[ ! -e "$dev/driver" ]] && continue
  [[ "$(basename "$(readlink "$dev/driver")")" != "mlx5_core" ]] && continue

  # Enumerate all netdevs under this PCI function (ports)
  if [[ -d "$dev/net" ]]; then
    for iface in "$dev"/net/*; do
      iface=$(basename "$iface")
      [[ "$iface" == "lo" ]] && continue

      echo "Configuring CX6 DX port: $iface"
      ethtool -C "$iface" adaptive-rx on adaptive-tx on
      ethtool -G "$iface" rx 8192 tx 8192
      ethtool -K "$iface" rx on tx on sg on tso on gso on gro off lro off
    done
  fi
done

# increase TCP max buffer size setable using setsockopt() to 512MB
sysctl -w net.core.rmem_max = 536870912
sysctl -w net.core.wmem_max = 536870912
# increase Linux autotuning TCP buffer limit to 256MB
sysctl -w net.ipv4.tcp_rmem = 4096 87380 268435456
sysctl -w net.ipv4.tcp_wmem = 4096 65536 268435456
# recommended for hosts with jumbo frames enabled
sysctl -w net.ipv4.tcp_mtu_probing=1
# recommended to enable 'fair queueing'
sysctl -w net.core.default_qdisc = fq
sysctl -w net.ipv4.conf.all.rp_filter=0
sysctl -w net.ipv4.conf.rdma.rp_filter=0
sysctl -w net.ipv4.conf.default.rp_filter=0


#### this is maxed out cx6-dx but we have rdma network with cx3pro so we need to keep it to cx3pro values
# allow TCP with buffers up to 2GB (Max allowed in Linux is 2GB-1)
#sysctl -w net.core.rmem_max=2147483647
#sysctl -w net.core.wmem_max=2147483647
# increase TCP autotuning buffer limits. 
#sysctl -w net.ipv4.tcp_rmem=4096 131072 1073741824 
#sysctl -w net.ipv4.tcp_wmem=4096 16384 1073741824
# recommended for hosts with jumbo frames enabled
#sysctl -w net.ipv4.tcp_mtu_probing=1
# recommended to enable 'fair queueing'
#sysctl -w net.core.default_qdisc = fq
# need to increase this to use MSG_ZEROCOPY
#sysctl -w net.core.optmem_max = 1048576 
#sysctl -w net.ipv4.conf.all.rp_filter=0
#sysctl -w net.ipv4.conf.default.rp_filter=0
