#!/bin/bash

#ethtool -K enp132s0 hw-tc-offload on tx on rx on tso on gso on gro on rxvlan on txvlan on
#ethtool -K enp132s0d1 hw-tc-offload on tx on rx on tso on gso on gro on rxvlan on txvlan on

# Unload bonding module 
modprobe -r bonding || true

# SETUP MTU
modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
ip link  add mlnx-bond type bond
ip link  set enp132s0 down
ip link set enp132s0d1 down
ip link  set enp132s0 master mlnx-bond
ip link  set enp132s0d1 master mlnx-bond
ip link  set mlnx-bond up

# SETUP DRBD-RDMA REPLICATION
ip link add link mlnx-bond name drbd-rdma type vlan id 5
ip link set drbd-rdma mtu 9000
ip link set drbd-rdma up
ip addr add 4.0.0.7/24 dev drbd-rdma

# SETUP DRBD REPLICATION
ip link add link mlnx-bond name drbd type vlan id 10 
ip link set drbd mtu 9000
ip link set drbd up
ip addr add 4.1.0.7/24 dev drbd

# SETUP LINSTOR MGMT 
ip link add link mlnx-bond name linstor-mgmt type vlan id 20
ip link set linstor-mgmt up
ip addr add 4.2.0.7/24 dev linstor-mgmt

# SETUP OVN NETWORK
ip link add link mlnx-bond name ovn-mgmt type vlan id 30
ip link set ovn-mgmt up
ip addr add 4.3.0.7/24 dev ovn-mgmt
