version = 5.6.0
archive_dir = /etc/letsencrypt/archive/npm-60
cert = /etc/letsencrypt/live/npm-60/cert.pem
privkey = /etc/letsencrypt/live/npm-60/privkey.pem
chain = /etc/letsencrypt/live/npm-60/chain.pem
fullchain = /etc/letsencrypt/live/npm-60/fullchain.pem
[renewalparams]
account = 15f8c8d267ae02273560b81ad5e07480
key_type = rsa
elliptic_curve = secp384r1
preferred_chain = ISRG Root X1
pref_challs = http-01,
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-lib
logs_dir = /data/logs
authenticator = webroot
webroot_path = /data/letsencrypt-acme-challenge,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
incus.calpolynglab.com = /data/letsencrypt-acme-challenge
