#!/bin/bash

ethtool -G enp175s0 rx 8192 tx 8192
ethtool -K enp175s0 rx on 
ethtool -K enp175s0 tx on 
ethtool -K enp175s0 sg on 
ethtool -K enp175s0 tso on 
ethtool -K enp175s0 gso on 
ethtool -K enp175s0 gro on 
ethtool -K enp175s0 rxvlan on 
ethtool -K enp175s0 txvlan on 
ethtool -K enp175s0 rx-checksum on 
ethtool -K enp175s0 tx-checksum on 
ethtool -K enp175s0 tx-udp_tnl-segmentation on

ethtool -G enp175s0d1 rx 8192 tx 8192
ethtool -K enp175s0d1 rx on 
ethtool -K enp175s0d1 tx on 
ethtool -K enp175s0d1 sg on 
ethtool -K enp175s0d1 tso on 
ethtool -K enp175s0d1 gso on 
ethtool -K enp175s0d1 gro on 
ethtool -K enp175s0d1 rxvlan on 
ethtool -K enp175s0d1 txvlan on 
ethtool -K enp175s0d1 rx-checksum on 
ethtool -K enp175s0d1 tx-checksum on 
ethtool -K enp175s0d1 tx-udp_tnl-segmentation on
# Unload bonding module 
modprobe -r bonding || true

# SETUP MTU
modprobe bonding mode=802.3ad miimon=100 lacp_rate=1 xmit_hash_policy=layer3+4
ip link  add mlnx-bond type bond
ip link  set enp175s0 down
ip link  set enp175s0d1 down
ip link  set enp175s0 master mlnx-bond
ip link  set enp175s0d1 master mlnx-bond
ip link  set mlnx-bond up

# SETUP DRBD REPLICATION
ip link add link mlnx-bond name drbd type vlan id 10
ip link set drbd up
ip addr add 4.1.0.10/24 dev drbd

# SETUP LINSTOR MGMT 
ip link add link mlnx-bond name linstor-mgmt type vlan id 20
ip link set linstor-mgmt up
ip addr add 4.2.0.10/24 dev linstor-mgmt

# SETUP OVN NETWORK
ip link add link mlnx-bond name ovn-mgmt type vlan id 30
ip link set ovn-mgmt up
ip addr add 4.3.0.10/24 dev ovn-mgmt

# SETUP INCUS NETWORK
ip link add link mlnx-bond name incus-mgmt type vlan id 40
ip link set incus-mgmt up
ip addr add 4.4.0.10/24 dev incus-mgmt

# SETUP INCUS NETWORKS
ip link add link mlnx-bond name infra type vlan id 50
ip link set infra up

ip link add link mlnx-bond name admin-labs type vlan id 60
ip link set admin-labs up

ip link add link mlnx-bond name bdebruhl type vlan id 70
ip link set bdebruhl up

ip link add link mlnx-bond name bhartma type vlan id 80
ip link set bhartma up

ip link add link mlnx-bond name sbeard type vlan id 90
ip link set sbeard up

ip link add link mlnx-bond name dofang type vlan id 100
ip link set dofang up
